import type { AndroidSymbol, SFSymbol } from "expo-symbols";

const androidSymbols = {
  "exclamationmark.triangle.fill": "warning",
  "exclamationmark.triangle": "warning",
  "checkmark.seal.fill": "verified",
  "book.fill": "menu_book",
  "briefcase.fill": "work",
  "bus.fill": "directions_bus",
  calendar: "calendar_month",
  "camera.fill": "camera_alt",
  sparkles: "auto_awesome",
  "cup.and.saucer.fill": "coffee",
  "birthday.cake.fill": "cake",
  "creditcard.fill": "credit_card",
  "diamond.fill": "diamond",
  "dumbbell.fill": "fitness_center",
  "heart.fill": "favorite",
  "gamecontroller.fill": "sports_esports",
  "gift.fill": "card_giftcard",
  "cross.case.fill": "medical_services",
  "house.fill": "home",
  "photo.fill": "photo",
  "receipt.fill": "receipt_long",
  "washer.fill": "local_laundry_service",
  "arrow.down.circle.fill": "arrow_circle_down",
  "arrow.up.circle.fill": "arrow_circle_up",
  "tag.fill": "sell",
  "pin.fill": "push_pin",
  "graduationcap.fill": "school",
  "square.and.arrow.up": "share",
  "basket.fill": "shopping_basket",
  smartphone: "smartphone",
  "tshirt.fill": "checkroom",
  "person.2.fill": "group",
  "wallet.pass.fill": "wallet",
  "drop.fill": "water_drop",
  "arrow.left.arrow.right": "swap_horiz",
  "arrow.left.arrow.right.circle.fill": "swap_horizontal_circle",
  "arrow.up.arrow.down": "swap_vert",
  "chart.pie.fill": "pie_chart",
  "bolt.fill": "bolt",
  "repeat.circle.fill": "repeat",
  plus: "add",
  "arrow.left": "arrow_back",
  "arrow.right": "arrow_forward",
  "chevron.left": "chevron_left",
  "chevron.right": "chevron_right",
  "chevron.down": "expand_more",
  "chevron.up": "expand_less",
  checkmark: "check",
  xmark: "close",
  "eye.fill": "visibility",
  "eye.slash.fill": "visibility_off",
  "person.crop.circle": "account_circle",
  "person.badge.key": "passkey",
  "arrow.triangle.2.circlepath": "sync",
  "rectangle.portrait.and.arrow.right": "logout",
  moon: "dark_mode",
  paintpalette: "palette",
  "textformat.size": "format_size",
  "dollarsign.circle": "paid",
  globe: "language",
  "arrow.clockwise.circle": "update",
  "info.circle": "info",
  "hand.raised": "privacy_tip",
  "bubble.left.and.bubble.right": "support_agent",
  "hand.wave": "waving_hand",
  envelope: "mail",
  "pencil.circle.fill": "edit",
  "trash.fill": "delete",
  "checkmark.circle.fill": "check_circle",
  "calendar.badge.clock": "event_repeat",
  "calendar.badge.plus": "event_upcoming",
  "bag.fill": "shopping_bag",
  photo: "photo",
  "banknote.fill": "payments",
  "car.fill": "directions_car",
  "doc.text": "description",
  "doc.text.fill": "description",
  "line.3.horizontal.decrease": "filter_list",
  "play.rectangle.fill": "smart_display",
  "square.grid.2x2": "grid_view",
  "sun.max.fill": "wb_sunny",
} as const satisfies Record<string, AndroidSymbol>;

export function getPlatformSymbol(name: SFSymbol) {
  const android = androidSymbols[name as keyof typeof androidSymbols] ?? "help";
  return { ios: name, android, web: android } as const;
}
